#BSUB -J ESPRESSO_Q
#BSUB -W 96:00
#BSUB -o /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/Espresso/outQ
#BSUB -e /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/Espresso/outQ
#BSUB -q e40long 
#BSUB -n 5
#BSUB -M 400
#BSUB -R rusage[mem=400]
#BSUB -N
#BSUB -B
#BSUB -u EKilinc@mdanderson.org

module add R/4.3.1
module add samtools/1.16
eval "$(/risapps/rhel8/miniconda3/py39_4.12.0/bin/conda shell.bash hook)"
module add perl/5.36.1
module add blast/2.14.0
eval "$(/risapps/rhel8/miniconda3/py39_4.12.0/bin/conda shell.bash hook)"


module add hmmer/3.3.2
eval "$(/risapps/rhel8/miniconda3/py39_4.12.0/bin/conda shell.bash hook)"
conda activate blast-2.14.0 
conda activate --stack samtools-1.16.1 
conda activate --stack hmmer-3.3.2

base_espresso=/rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/software/espresso/src
espresso_script=/rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/Espresso
base_ref=/rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/ref
out_folder=/rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/Espresso/Espresso_outS

perl $base_espresso/ESPRESSO_Q.pl \
-L $out_folder/sampleHash.tsv.updated \
-A $base_ref/gencode.v44.annotation.gtf \
-T 5

conda deactivate
conda deactivate
conda deactivate
conda deactivate
