#BSUB -J espresso_c[1-72]
#BSUB -W 72:00
#BSUB -o /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/Flair/out/Output_%J_%I.out
#BSUB -e /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/Flair/out/Output_%J_%I.err 
#BSUB -q long 
#BSUB -n 5 			# Request all procs
#BSUB -M 25			# Maximum!
#BSUB -R rusage[mem=125]
#BSUB -u EKilinc@mdanderson.org	# This is useful for error reporting
## explanation of arguments above:
## -J arbitrary job name
## -W wallclock in hour:min
## -o use this or output (stdout) will be sent via email!
## -e use this or errors (stderr) will be sent via email!
## -q queue name (short is the default)
## -n min_proc[,max_proc]  number of processors required (28=entire node)
## -M memory in GB 
## -R memory in GB 
## -u EmailAddress

module load R/4.3.1
module load samtools
eval "$(/risapps/rhel8/miniconda3/py39_4.12.0/bin/conda shell.bash hook)"
conda activate samtools-1.16.1
module load python/3.11.3
bedtools=/rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/software/bedtools

cd /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/Flair

Rscript flair_correct.R --sample $LSB_JOBINDEX