#BSUB -J nanofiltfq
#BSUB -W 48:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/data/Placenta_LRRNAseq/NanoFilt/out_fastqc/Output_%J_%I.out
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/data/Placenta_LRRNAseq/NanoFilt/out_fastqc/Output_%J_%I.out
#BSUB -q long 
#BSUB -n 1 			# Request all procs
#BSUB -M 50			# Maximum!
#BSUB -R rusage[mem=50]
#BSUB -u EKilinc@mdanderson.org	# This is useful for error reporting
## explanation of arguments above:
## -J arbitrary job name
## -W wallclock in hour:min
## -o use this or output (stdout) will be sent via email!
## -e use this or errors (stderr) will be sent via email!
## -q queue name (short is the default)
## -n min_proc[,max_proc]  number of processors required (28=entire node)
## -M memory in GB 
## -R memory in GB 
## -u EmailAddress

module load fastqc/0.11.9
eval "$(/risapps/rhel8/miniconda3/py39_4.12.0/bin/conda shell.bash hook)"
conda activate fastqc-0.11.9

cd /rsrch5/home/epi/bhattacharya_lab/data/Placenta_LRRNAseq/NanoFilt/trim

fastqc -o /rsrch5/home/epi/bhattacharya_lab/data/Placenta_LRRNAseq/NanoFilt/fastqc_results *.gz

conda deactivate