#BSUB -J joinfq
#BSUB -W 48:00
#BSUB -o /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/out_j
#BSUB -e /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/out_j
#BSUB -q long 
#BSUB -n 1 			# Request all procs
#BSUB -M 50			# Maximum!
#BSUB -R rusage[mem=50]
#BSUB -u EKilinc@mdanderson.org	# This is useful for error reporting
## explanation of arguments above:
## -J arbitrary job name
## -W wallclock in hour:min
## -o use this or output (stdout) will be sent via email!
## -e use this or errors (stderr) will be sent via email!
## -q queue name (short is the default)
## -n min_proc[,max_proc]  number of processors required (28=entire node)
## -M memory in GB 
## -R memory in GB 
## -u EmailAddress


temp_file="/rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/pass/combined_temp.fastq"
output_file="/rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/pass/combined.fastq.gz"

# Clear any existing temporary output file
: > $temp_file

for file in /rsrch5/scratch/neuro_rsrch/ekilinc/lnrnatrial/placenta_trial/pass/*.fastq.gz
do
    zcat "$file" >> "$temp_file"
done

gzip -c "$temp_file" > "$output_file"

# Remove the temporary file
rm "$temp_file"